name: Publish for Windows

on:
  workflow_dispatch:

jobs:
  publish-windows:
    uses: madamov/ObjoPublisher/.github/workflows/publish_objo_windows.yml@v1
    with:
      solution-file: "4D Downloader.objosln"
      project-file: "Projects/4D Downloader/project.json"
      application-name: 4D Downloader
      artifact-name: 4ddownloader-windows-publish
      output-directory: Publish
      targets: win-x64

      # Optional. Leave this out to detect the latest version.
      # objo-version: 26.7.1


    secrets:
      objo-license: ${{ secrets.OBJO_LICENSE }}

  download-windows-artifact:
    name: Download and upload published Windows artifact
    needs: publish-windows
    runs-on: windows-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: 4ddownloader-windows-publish
          path: downloaded-artifacts\4ddownloader-windows-publish

      - name: Show downloaded files
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          Write-Host "Downloaded artifact contents:"

          Get-ChildItem `
            -Path "downloaded-artifacts" `
            -Recurse `
            -File |
            Select-Object FullName, Length |
            Format-Table -AutoSize
